apiVersion: v2
name: ejabberd
description: ejabberd XMPP server helm chart
type: application
version: 0.3.2
appVersion: "78f81de252dc932cd47b91d1a84ca8e8f0647498-k8s3"
keywords:
  - xmpp
  - mqtt
  - sip
  - stun
  - turn

maintainers:
  - name: saarko
    email: saarko@tutanota.com
